import React, {ReactNode} from 'react';
import ResponsiveAppBar from "../common/navBar";
import Head from "next/head";
import {Box} from "@mui/material";
import Footer from "../common/footer";

type Props = {
    children: ReactNode;
    title: string;
};

const HomeLayout = ({children, title }: Props) => {
    return (
        <Box>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ResponsiveAppBar sx={{mt: '20rem'}}/>
                {children}
            <Footer  props={''} />

        </Box>

    )
}

export default HomeLayout